pgadmin:
  image: dpage/pgadmin4
  ports:
    - "8081:80"
  environment:
    - PGADMIN_DEFAULT_EMAIL=me@example.com
    - PGADMIN_DEFAULT_PASSWORD=password
  links:
    - db
db:
  image: hackathon/db
  environment:
    - POSTGRES_PASSWORD=guest
  volumes:
    - ./dB:/docker-entrypoint-initdb.d
node:
  image: "node:8"
  user: "node"
  working_dir: /home/node/app
  environment:
    - NODE_ENV=develop
  volumes:
    - ./:/home/node/app
  ports:
    - "8080:5000"
  command: "node server.js"
  links:
    - db
