INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Xtreme Laser Tag');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Rapid Fire');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Meltdown');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Tech-Trike-Athlon');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Monster Jenga');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Splash!');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Crazy Catapult Cornhole');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Soccer Darts');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Monster Scrabble');
INSERT INTO games (gameid, gamename) VALUES (DEFAULT, 'Drop It like Its Host');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Number Ninjas');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Binary Code');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'BWhen Pigs Fly');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'I Got You Babe');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Dont Go Bacon My Heart');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Swine Time');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Pulled Porkers');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Thats Trough');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Lets Pig Out');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'We Put Pork on Your Fork');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Rump Roasters');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Snortin and Porkin');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Jargonauts');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Overrulers');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Mock On');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Bend & Snaps');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Courtroom Crew');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Rest My Case');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Dont Mock Us');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Cross Examiners');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Unreasonable Doubt');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'We’re Judgy');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Mighty Chondria');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Natural Selection');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'The Dork Side');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Wise Guys');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'The Black Holes');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Good Genes');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'The Fig Neutrons');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Mad Scientists');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Neon Rubindium (Ne-Rd)');
INSERT INTO teams (teamid, tname) VALUES (DEFAULT, 'Big Bang');

INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:00, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:01, 2, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:02, 3, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:03, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:04, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:05, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:06, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:07, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:08, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:09, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:10, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:11, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:12, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:13, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:14, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:15, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:16, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:17, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:18, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:19, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:20, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:21, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:22, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:23, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:24, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:25, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:26, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:27, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:28, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:29, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:30, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:31, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:32, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:33, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:34, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:35, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:36, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:37, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:38, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:39, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:40, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:41, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:42, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:43, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:45, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:46, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:47, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:48, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:49, 1, 1');
INSERT INTO results (roundid, rtimestamp, teamid, gameid) VALUES (DEFAULT, '09:50, 1, 1');
INSERT INTO scores (roundid, teamid, score) VALUES (1, 1, 101);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 2, 102);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 3, 103);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 4, 104);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 5, 105);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 6, 106);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 7, 107);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 8, 108);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 9, 109);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 10, 110);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 11, 111);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 12, 112);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 13, 113);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 14, 114);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 15, 115);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 16, 116);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 17, 117);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 18, 118);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 19, 119);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 20, 120);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 21, 121);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 22, 122);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 23, 123);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 24, 124);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 25, 125);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 26, 126);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 27, 127);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 28, 128);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 29, 129);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 30, 130);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 31, 131);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 32, 132);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 33, 133);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 34, 134);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 35, 135);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 36, 136);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 37, 137);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 38, 138);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 39, 139);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 40, 140);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 41, 141);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 42, 142);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 43, 143);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 44, 144);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 45, 145);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 46, 146);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 47, 147);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 48, 148);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 49, 149);
INSERT INTO scores (roundid, teamid, score) VALUES (1, 50, 150);
